name: "thois-production"

services:
  rails-app:
    build: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 80 -b '0.0.0.0'"
    ports:
      - "80:80"
    volumes:
      - ".:/rails"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - THOIS_DATABASE_PASSWORD=${THOIS_DATABASE_PASSWORD}

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: thois
      POSTGRES_PASSWORD: ${THOIS_DATABASE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
