development:
  clients:
    default:
      uri: 'mongodb+srv://thois:<%= Rails.application.credentials.db.cloud.password %>@cluster0.sfcmp8m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      options:
        server_selection_timeout: 5

production:
  clients:
    default:
      uri: 'mongodb+srv://thois:<%= Rails.application.credentials.db.cloud.password %>@cluster0.sfcmp8m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      uri: 'mongodb+srv://thois:<%= Rails.application.credentials.db.cloud.password %>@cluster0.sfcmp8m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
      options:
        server_selection_timeout: 5
